language: python

python:
  - "3.5"
  - "3.6"

sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq qttools5-dev-tools
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - pip install -r requirements.txt

script:
  - python example/example_pyqt5.py --travis

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: Uvemode
  password: $PYPI_PASSWORD
  on:
    tags: true
    repo: Uvemode/qcrimsostyle
    branch: master
    python: '3.5'